GET 
https://content-sharing-backed.onrender.com/posts

###

POST http://localhost:3000/register
Content-Type: application/json

}
  "name": "Sadhik Sheik",
  "password": "sadhik@123"
}

### 
POST http://localhost:3000/login
Content-Type: application/json

}
  "name": "Sadhik Sheik",
  "password": "sadhik@123"
}