POST https://content-sharing-backed.onrender.com/register
Content-Type: application/json

{
  "name": "Sadhik Sheik",
  "password": "sadhik@123"
}

### 
POST http://localhost:3003/login
Content-Type: application/json

{
  "name": "Leo Motto",
  "password": "leo@123"
}

###
GET http://localhost:3003/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiTGVvIE1vdHRvIiwiaWF0IjoxNjkzNDE2MTA1fQ.nU4lnw30PGfeCTLH8sURzkHzdl1mqUEcrvz1yF4ET3Y
###

GET http://localhost:3003/posts/2
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiTGVvIE1vdHRvIiwiaWF0IjoxNjkzNDE2MTA1fQ.nU4lnw30PGfeCTLH8sURzkHzdl1mqUEcrvz1yF4ET3Y

###
PUT  http://localhost:3003/posts/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiTGVvIE1vdHRvIiwiaWF0IjoxNjkzNDE2MTA1fQ.nU4lnw30PGfeCTLH8sURzkHzdl1mqUEcrvz1yF4ET3Y

{
  "post_text":"hii im leo and im new to this platform "
}
###
POST http://localhost:3003/posts
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiU2F0aGlzaCBQeWRpIiwiaWF0IjoxNjkzNDE0MzI1fQ.HQeSICVwY83rb-uFMufvu9C3F0OMYhUZve55JCVgzCU

{
  "post_text": "Hii im leo im a mechanical engineer",
  "likes":12,
  "user_id":3,
  "user_name": "Sadhik Sheik"
}

###
DELETE http://localhost:3003/posts/12
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiU2F0aGlzaCBQeWRpIiwiaWF0IjoxNjkzNDE0MzI1fQ.HQeSICVwY83rb-uFMufvu9C3F0OMYhUZve55JCVgzCU

